Pd/make post
AzzieDevelopment/tiger-talks pull request #38
Opened 2021-11-20 03:17 UTC by pnguye18

2021-11-20 03:22 UTC, pnguye18 commented
@samanthahallcox Not sure if I did this pull request correctly, if you could look at it when you have the time.

2021-11-21 17:22 UTC, samanthahallcox commented on angular/src/app/angular-material.module.ts
> +import { CommonModule } from '@angular/common';
remove angular-material.module.ts

2021-11-21 17:24 UTC, samanthahallcox commented on angular/src/app/app.module.ts
> +import { AngularMaterialModule } from './angular-material.module';
remove all Angular Material related imports

2021-11-21 17:24 UTC, samanthahallcox commented on angular/src/app/make-post/make-post.component.html
> +<html>
remove `html`, `head`, and `body` tags

2021-11-21 17:25 UTC, samanthahallcox commented on angular/src/app/make-post/make-post.component.ts
> +import { MatChipInputEvent } from '@angular/material/chips';
Remove Angular Material imports

2021-11-21 17:26 UTC, samanthahallcox commented on angular/src/app/make-post/make-post.component.ts
> +export interface Category{
should this be extracted to the Post interface?

2021-11-21 17:26 UTC, samanthahallcox commented on angular/src/app/make-post/make-post.component.css
> +.material-icons{
remove Material icon rule

2021-11-21 17:27 UTC, samanthahallcox commented on package.json
> +    "@angular/material": "^12.2.12",
use `npm` to remove angular material dependencies 

https://docs.npmjs.com/uninstalling-packages-and-dependencies

2021-11-21 17:30 UTC, samanthahallcox requested changes
See my comments above for necessary changes

2021-11-21 17:31 UTC, samanthahallcox commented on angular/src/app/make-post/make-post.component.ts
> +export interface Category{
to clarify, I meant the category interface. although I'm not sure if this was just used with the chip thing

2021-11-21 17:35 UTC, samanthahallcox commented on angular/src/app/app-routing.module.ts
> +import { SignInComponent } from './sign-in/sign-in.component';
remove duplicate import (SignIn)

2021-11-21 17:35 UTC, samanthahallcox commented on angular/src/app/app-routing.module.ts
> +  { path: 'makePost', component: MakePostComponent},
change casing of makePost to makepost to match other route casing

2021-11-21 17:46 UTC, samanthahallcox commented on angular/src/app/make-post/make-post.component.html
> +                <br>
did we want a category field?

2021-11-29 20:11 UTC, closed without merging